# Generated by Django 6.0 on 2026-06-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_locataire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bail',
            name='type_bail',
            field=models.CharField(choices=[('VIDE', 'Location vide'), ('MEUB', 'Location meublée'), ('SAIS', 'Location saisonnière'), ('COMM', 'Bail commercial'), ('PROF', 'Bail professionnel')], default='VIDE', max_length=4, verbose_name='Type de bail'),
        ),
    ]
